spring:
  #mq
  rabbitmq:
    host: 47.94.86.230
    port: 5672
    virtual-host: /
    username: admin
    password: adminzelei
    listener:
      simple:
        prefetch: 1 # 每次只能获取一条消息 处理完成后才能获取下一个消息

server:
  port: 8090
